### PR TITLE
Add env namespace handling

### PR DESCRIPTION
**Pull request by elwinar**
This add namespace env handling, which allow to re-use configuration struct that define an env default.

### CODE REVIEW

**Comment by elwinar** [comment]
@jessevdk ?

**Comment by ccoVeille** [comment]
hi guys, is there any reason why this MR has not been reviewed for the past 3 months ?

This MR contains exactly what we were looking for; this change could be very interesting for us.

**Comment by reddec** [comment]
@jessevdk could you please make a review?

**Comment by elwinar** [comment]
Done.

**Comment by elwinar** [comment]
Conflicts are resolved, CI fails because of some badly outdated dependency (golint in this case), tests ran by hand are fine.

**Pull request merged**
