### PR TITLE
#245 - Add ability to specify delimiter for slice flags

### PR DESCRIPTION
**Pull request by pazderak**
Hi, I implemented #245, could you please check it?

### CODE REVIEW

**Comment by pazderak** [comment]
@jessevdk

**Comment by pazderak** [comment]
Hi @jessevdk, any chance to look on it? Thanks.

**Comment by ccoVeille** [comment]
If I may, why no rebase -i your two commits into one ?

It appears to me the second one is a commit to find a better solution of what was written in the first one.

Sorry if I missed something

**Comment by pazderak** [comment]
Correct, will do. Thanks.

**Pull request closed without merging**
