### PR TITLE
Fix for passing global flags after subcommands 

### PR DESCRIPTION
**Pull request by peterebden**
e.g. `program command subcommand --flag`

### CODE REVIEW

**Comment by jessevdk** [comment]
Issue #141 fixed this already! Sorry for letting the PR go ignored :(, I really do appreciate contributions.

**Comment by peterebden** [comment]
Thanks, but I don't think this is fixed on master for my use case. #141 allowed passing global flags after a command which is great, but it still doesn't work after a following subcommand, eg. "myprogram -v command subcommand" != "myprogram command subcommand -v".
I think it's just a small oversight where a loop terminates too early?

**Comment by jessevdk** [comment]
Nice catch! It was indeed wrongly iterating over all the parents. It was also iterating over them in reverse order. I've pushed a fix + tests for both issues. Should be working correctly now.

**Comment by peterebden** [comment]
Awesome, thanks! And thanks for the library, it's been ideal for what we needed :)

**Pull request closed without merging**
